# Generated by Django 4.0.2 on 2022-03-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='web_id',
            field=models.CharField(max_length=100),
        ),
    ]
