# Generated by Django 4.0.2 on 2022-03-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0002_product_count_alter_product_web_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['id'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категотии'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['id'], 'verbose_name': 'подкатегория', 'verbose_name_plural': 'подкатегори'},
        ),
    ]
