# Generated by Django 4.0.2 on 2022-03-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0007_category_parent_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'подкатегория', 'verbose_name_plural': 'подкатегори'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
