# Generated by Django 4.0.2 on 2022-03-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0008_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категотии'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
    ]
