# Generated by Django 4.0.2 on 2022-03-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopper', '0009_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
